//
//  FavouriteData.swift
//  Umm
//
//  Created by Kai-Hsuan Lin on 07/05/2025
//

import Foundation

// Restaurant: 50
struct CategoryTypeData {
    static let RestaurantCategories = [
        "African Food",
        "American Food",
        "Ausian Food",
        "Australian Food",
        "BBQ",
        "Bengali",
        "Bistro",
        "British",
        "Buffet",
        "Café",
        "Chinese Food",
        "Continental",
        "Dessert",
        "Dim Sum",
        "European Food",
        "Fast Food",
        "Fine Dining",
        "French",
        "Fusion",
        "Healthy Food",
        "Hot Pot",
        "Indian Food",
        "Italian Food",
        "Japanese",
        "Kebab Shop",
        "Korean",
        "Malaysia Food",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Nepali",
        "North Indian",
        "Omakas",
        "Punjabi",
        "Ramen",
        "SeaFood",
        "Singaporean",
        "South American",
        "South Indian",
        "Spanish",
        "Steakhouse",
        "Street Food",
        "Sushi Bar",
        "Taiwanese Food",
        "Thai",
        "Tibetan",
        "Turkish Food",
        "Vegan",
        "Vegetarian",
        "Vietnamese Food",
    ]

    // NonAlcoholic: 25
    static let BeverageCategoriesNonAlcoholic = [
        "Bubble Tea",
        "Buttermilk",
        "Coconut Water",
        "Coffee",
        "Coke",
        "Energy Drink",
        "Flavored Water",
        "Herbal Tea",
        "Hot Chocolate",
        "Juice",
        "Lassi",
        "Lemonade",
        "Matcha",
        "Milk",
        "Milkshake",
        "Mocktail",
        "Smoothie",
        "Soda",
        "Soft Drinks",
        "Sports Drinks",
        "Sparkling Water",
        "Tea",
        "Tonic Water",
        "Water",
        "Yogurt Drinks",
    ]
    
    // Alcoholic: 25
    static let BeverageCategoriesAlcoholic = [
        "Beer",
        "Brandy",
        "Champagne",
        "Cocktail",
        "Craft Beer",
        "Espresso Martini",
        "Gin",
        "Hard Cider",
        "Margarita",
        "Martini",
        "Mojito",
        "Negroni",
        "Old Fashioned",
        "Red Wine",
        "Rosé Wine",
        "Rum",
        "Sake",
        "Soju",
        "Sparkling Wine",
        "Tequila",
        "Vodka",
        "Wine",
        "White Wine",
        "Whiskey",
        "Whiskey Sour"
    ]
}
