import Foundation

struct CategoryTypeData {
    static let RestaurantCategories = [
        "African",
        "American",
        "Australian",
        "BBQ",
        "Bengali",
        "Bistro",
        "British",
        "Buffet",
        "Café",
        "Chinese",
        "Continental",
        "Dim Sum",
        "European",
        "Fast Food",
        "Fine Dining",
        "French",
        "Fusion",
        "Gujarati",
        "Healthy",
        "Hot Pot",
        "Indian",
        "Italian",
        "Japanese",
        "Kebab Shop",
        "Korean",
        "Malaysia",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Nepali",
        "North Indian",
        "Omakas",
        "Punjabi",
        "Rajasthani",
        "Ramen",
        "Seafood",
        "Singaporean",
        "South American",
        "South Indian",
        "Spanish",
        "Steakhouse",
        "Street Food",
        "Sushi Bar",
        "Taiwanese",
        "Thai",
        "Tibetan",
        "Turkish",
        "Vegan",
        "Vegetarian",
        "Vietnamese",
    ]

    static let BeverageCategoriesNonAlcoholic = [
        "Bubble Tea",
        "Buttermilk",
        "Coconut Water",
        "Coffee",
        "Coke",
        "Energy Drink",
        "Flavored Water",
        "Herbal Tea",
        "Hot Chocolate",
        "Juice",
        "Lassi",
        "Lemonade",
        "Matcha",
        "Milk",
        "Milkshake",
        "Mocktail",
        "Smoothie",
        "Soda",
        "Soft Drinks",
        "Sports Drinks",
        "Sparkling Water",
        "Tea",
        "Yogurt Drinks"
    ]
    
    static let BeverageCategoriesAlcoholic = [
        "Beer",
        "Brandy",
        "Champagne",
        "Cocktail",
        "Craft Beer",
        "Gin",
        "Hard Cider",
        "Red Wine",
        "Rosé Wine",
        "Rum",
        "Sake",
        "Soju",
        "Tequila",
        "Vodka",
        "Wine",
        "White Wine",
        "Whiskey"
    ]
}
