//
//  FavouriteData.swift
//  Umm
//
//  Created by Kai-Hsuan Lin on 07/05/2025
//

import Foundation

// Restaurant: 50
struct CategoryTypeData {
    static let RestaurantCategories = [
        "African",
        "American",
        "Ausian",
        "Australian",
        "BBQ",
        "Bengali",
        "Bistro",
        "British",
        "Buffet",
        "Café",
        "Chinese",
        "Continental",
        "Dessert",
        "Dim Sum",
        "European",
        "Fast Food",
        "Fine Dining",
        "French",
        "Fusion",
        "Healthy",
        "Hot Pot",
        "Indian",
        "Italian",
        "Japanese",
        "Kebab Shop",
        "Korean",
        "Malaysia",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Nepali",
        "North Indian",
        "Omakas",
        "Punjabi",
        "Ramen",
        "Seafood",
        "Singaporean",
        "South American",
        "South Indian",
        "Spanish",
        "Steakhouse",
        "Street Food",
        "Sushi Bar",
        "Taiwanese",
        "Thai",
        "Tibetan",
        "Turkish",
        "Vegan",
        "Vegetarian",
        "Vietnamese",
    ]

    // NonAlcoholic: 25
    static let BeverageCategoriesNonAlcoholic = [
        "Bubble Tea",
        "Buttermilk",
        "Coconut Water",
        "Coffee",
        "Coke",
        "Energy Drink",
        "Flavored Water",
        "Herbal Tea",
        "Hot Chocolate",
        "Juice",
        "Lassi",
        "Lemonade",
        "Matcha",
        "Milk",
        "Milkshake",
        "Mocktail",
        "Smoothie",
        "Soda",
        "Soft Drinks",
        "Sports Drinks",
        "Sparkling Water",
        "Tea",
        "Tonic Water",
        "Water",
        "Yogurt Drinks",
    ]
    
    // Alcoholic: 25
    static let BeverageCategoriesAlcoholic = [
        "Beer",
        "Brandy",
        "Champagne",
        "Cocktail",
        "Craft Beer",
        "Espresso Martini",
        "Gin",
        "Hard Cider",
        "Margarita",
        "Martini",
        "Mojito",
        "Negroni",
        "Old Fashioned",
        "Red Wine",
        "Rosé Wine",
        "Rum",
        "Sake",
        "Soju",
        "Sparkling Wine",
        "Tequila",
        "Vodka",
        "Wine",
        "White Wine",
        "Whiskey",
        "Whiskey Sour"
    ]
}
